Repository MichailZyusko/benefit.mobile, pull requests merged in 2022-11, with the labels that each got.

#50 refactor: strong ts support (CI check)
  .github/workflows/CI.yml
  package.json
Labels: CI

#52 fix: allow traffic without certificates
  android/app/src/main/AndroidManifest.xml
Labels: bug

#54 fix: small UI fix
  src/api/products/index.ts
  src/components/ModalWindow/index.tsx
  src/components/ModalWindow/styles.ts
  src/components/StoreLogo/index.tsx
  src/screens/home/index.tsx
Labels: bug

#55 fix/UI&UX fixes
  src/components/ModalWindow/index.tsx
  src/components/ModalWindow/styles.ts
  src/components/ProductCard/Components.tsx
  src/components/StoreLogo/index.tsx
  src/components/StoreLogo/styles.ts
Labels: bug, enhancement

#56 feature: Allow filter goods by stores
  package-lock.json
  package.json
  src/api/apiClient.ts
  src/api/products/index.ts
  src/api/stores/index.ts
  src/components/StoreLogo/constants.ts
  src/errors/InDevelopment/index.tsx
  src/screens/home/Components.tsx
  src/screens/home/index.tsx
  src/screens/home/slicer.ts
  src/screens/home/styles.ts
  src/types/store.ts
Labels: enhancement

#57 Feature/allow filter products by store
  src/components/StoreLogo/constants.ts
  src/components/StoreLogo/styles.ts
  src/screens/home/Components.tsx
  src/screens/home/index.tsx
  src/screens/home/styles.ts
Labels: bug
